name: swabber
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - scipy
  - pip
  - cython
  - tqdm
  - yaml
  - pyyaml
  - notebook
  - tensorboard
  - pytorch
  - seaborn
  - mesa
  - pytest
  - pylint